import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { Nunito_Sans } from "next/font/google";

import {
  THEME_COOKIE_NAME,
  LIGHT_COLORS,
  DARK_COLORS,
} from "@/constants";
import "./globals.css";
import LanguageProvider from "@/components/LanguageProvider";
import RouterProvider from "@/components/RouterProvider";
import Header from "@/components/Header";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const acceptLanguage = (await headers()).get("accept-language");
  const lang = acceptLanguage?.split(/[,;]/)[0] || "en-US";

  const savedTheme = (await cookies()).get(THEME_COOKIE_NAME);
  const theme = savedTheme?.value || "light";

  const themeColors = theme === "light" ? LIGHT_COLORS : DARK_COLORS;

  return (
    <html
      lang={lang}
      data-color-theme={theme}
      className={nunitoSans.variable}
      style={themeColors as React.CSSProperties}
    >
      <body>
        <LanguageProvider lang={lang}>
          <RouterProvider>
            <Header defaultTheme={theme as "light" | "dark"} />
            {children}
          </RouterProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
