import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Nunito_Sans } from "next/font/google";

import { THEME_COOKIE_NAME, LIGHT_COLORS, DARK_COLORS } from "@/constants";
import DarkLightToggle from "@/components/DarkLightToggle";
import "./globals.css";

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const savedTheme = (await cookies()).get(THEME_COOKIE_NAME);
  const theme = savedTheme?.value || "light";

  const themeColors =
    theme === "light" ? LIGHT_COLORS : DARK_COLORS;

  return (
    <html
      lang="en"
      data-color-theme={theme}
      className={nunitoSans.variable}
      style={themeColors as React.CSSProperties}
    >
      <body>
        <header>
          <DarkLightToggle defaultTheme={theme as "light" | "dark"} />
        </header>
        {children}
      </body>
    </html>
  );
}
