export const THEME_COOKIE_NAME = "color-theme";

export const LIGHT_COLORS = {
  "--color-bg": "var(--color-white)",
  "--color-text": "var(--color-grey-950)",
  "--color-text-muted": "hsl(200, 24%, 40%)",
  "--color-accent": "hsl(202, 86%, 94%)",
  "--color-button-bg": "var(--color-white)",
  "--color-button-text": "var(--color-grey-950)",
  "--color-button-shadow": "0px 0px 7px rgba(0, 0, 0, 0.1)",
  "--color-header-bg": "var(--color-white)",
  "--color-header-text": "var(--color-grey-950)",
  "--color-header-shadow": "0px 2px 4px rgba(0, 0, 0, 0.0562443)",
  "--color-search-bg": "var(--color-white)",
  "--color-search-text": "var(--color-grey-950)",
  "--color-search-placeholder": "var(--color-grey-400)",
  "--color-search-icon": "var(--color-grey-400)",
  "--color-search-shadow": "0px 2px 9px rgba(0, 0, 0, 0.0532439)",
  "--color-card-bg": "var(--color-white)",
  "--color-card-text": "var(--color-grey-950)",
  "--color-card-shadow": "0px 0px 7px 2px rgba(0, 0, 0, 0.1)",
  "--color-dropdown-bg": "var(--color-white)",
  "--color-dropdown-text": "var(--color-grey-950)",
  "--color-dropdown-shadow": "0px 2px 9px rgba(0, 0, 0, 0.0532439)",
};

export const DARK_COLORS = {
  "--color-bg": "var(--color-blue-950)",
  "--color-text": "var(--color-white)",
  "--color-text-muted": "hsl(0, 0%, 100%)",
  "--color-accent": "hsl(209, 23%, 22%)",
  "--color-button-bg": "var(--color-blue-950)",
  "--color-button-text": "var(--color-white)",
  "--color-button-shadow": "0px 0px 7px rgba(0, 0, 0, 0.1)",
  "--color-header-bg": "var(--color-blue-900)",
  "--color-header-text": "var(--color-white)",
  "--color-header-shadow": "0px 2px 4px rgba(0, 0, 0, 0.0562443)",
  "--color-search-bg": "var(--color-blue-900)",
  "--color-search-text": "var(--color-white)",
  "--color-search-placeholder": "var(--color-white)",
  "--color-search-icon": "var(--color-white)",
  "--color-search-shadow": "0px 2px 9px rgba(0, 0, 0, 0.0532439)",
  "--color-card-bg": "var(--color-blue-900)",
  "--color-card-text": "var(--color-white)",
  "--color-card-shadow": "0px 0px 7px 2px rgba(0, 0, 0, 0.1)",
  "--color-dropdown-bg": "var(--color-blue-900)",
  "--color-dropdown-text": "var(--color-white)",
  "--color-dropdown-shadow": "0px 2px 9px rgba(0, 0, 0, 0.0532439)",
};
